-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  date_of_birth date not null,
  gender text not null,
  country text not null,
  language text not null
);

alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Set up Realtime!
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table profiles;

-- Tables for Friend and Couple Relationships

-- 1. Friend Requests
create table friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid references profiles not null,
  receiver_id uuid references profiles not null,
  status text check (status in ('pending', 'accepted', 'rejected')) default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(sender_id, receiver_id)
);

alter table friend_requests enable row level security;
create policy "Users can see their own friend requests." on friend_requests for select using (auth.uid() in (sender_id, receiver_id));
create policy "Users can insert their own friend requests." on friend_requests for insert with check (auth.uid() = sender_id);
create policy "Receivers can update the status of friend requests." on friend_requests for update using (auth.uid() = receiver_id);

-- 2. Friendships
create table friendships (
  id bigint generated by default as identity primary key,
  user1_id uuid references profiles not null,
  user2_id uuid references profiles not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user1_id, user2_id),
  constraint check_users_not_equal check (user1_id <> user2_id)
);

alter table friendships enable row level security;
create policy "Users can see their own friendships." on friendships for select using (auth.uid() in (user1_id, user2_id));

-- 3. Couple Requests
create table couple_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid references profiles not null,
  receiver_id uuid references profiles not null,
  status text check (status in ('pending', 'accepted', 'rejected')) default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(sender_id, receiver_id)
);

alter table couple_requests enable row level security;
create policy "Users can see their own couple requests." on couple_requests for select using (auth.uid() in (sender_id, receiver_id));
create policy "Users can insert their own couple requests." on couple_requests for insert with check (auth.uid() = sender_id);
create policy "Receivers can update the status of couple requests." on couple_requests for update using (auth.uid() = receiver_id);

-- 4. Couples
create table couples (
  id bigint generated by default as identity primary key,
  user1_id uuid references profiles not null unique,
  user2_id uuid references profiles not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint check_couple_users_not_equal check (user1_id <> user2_id)
);

alter table couples enable row level security;
create policy "Users can see their own couple relationship." on couples for select using (auth.uid() in (user1_id, user2_id));
